remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
title: Dinky theme
description: Dinky is a red hot theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
